config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }
  resources :users, except: :create
  get 'create_user' => 'users#add_new_user', as: :new_user_by_admin
  post 'create_user' => 'users#create', as: :create_user
  get 'wallet' => 'vacancies#wallet'


  post 'vacancies/:vacancy_id/update_with_modules', to: 'vacancies#update_with_modules'
  post 'vacancies/:vacancy_id/get_modules', to: 'vacancies#get_modules'

  # devise_for :users, controllers: {
  #       sessions: 'users/sessions'
  #     }

  resources :vacancies do
     resources :reactions
     resources :vacancy_steps
     resources :vacancy_modules
  end

  # resources :vacancy_steps
  resources :companies do
     resources :locations
  end

  root "vacancies#index"
end

app/models/vacancy.rb
class Vacancy < ApplicationRecord
   has_many :reactions, dependent: :destroy
   has_many :social_media_modules, dependent: :destroy
   # has_many :location

   attr_accessor :name, :module_horizontal_position, :module_vertical_position, :module_width, :module_height

   #contact-gegevens-module
   attr_accessor :contact_fields_name, :contact_fields_horizontal_position, :contact_fields_vertical_position, :contact_fields_width, :contact_fields_height

   #social-media-module
   attr_accessor :social_media_name, :social_media_horizontal_position, :social_media_vertical_position, :social_media_width, :social_media_height

   accepts_nested_attributes_for :social_media_modules

   serialize :modules_array, Hash

   def self.search(search)
      where("title LIKE ?", "%#{search}%")
   end

end

app/controllers/vacancies_controller.rb
class VacanciesController < ApplicationController
   # before_action :authenticate_user!, except: [:index, :show]
   before_action :authenticate_user!

   def index
      @vacancies = Vacancy.all

      if params[:search]
         @vacancies = Vacancy.search(params[:search]).order('online DESC', 'created_at DESC')
      else
         @vacancies = Vacancy.all.order('online DESC', 'created_at DESC')
      end

      respond_to do |format|
         format.html
         format.json { render :json => @vacancies }
      end
   end

   def new
      @vacancy = Vacancy.new
   end

   def create
      @vacancy = Vacancy.new(vacancy_params)

      if @vacancy.save
         # redirect_to @vacancy
         redirect_to vacancy_vacancy_steps_path(@vacancy)
      else
         render 'new'
      end
   end

   def show
      @vacancy = Vacancy.find(params[:id])

      respond_to do |format|
         format.html
         format.json { render :json => @vacancy }
      end
   end

   def edit
      @vacancy = Vacancy.find(params[:id])
   end

   def update
      @vacancy = Vacancy.find(params[:id])

      if @vacancy.update(params[:vacancy].permit(:title, :description, :demands, :branche, :education_level, :experience, :location_id, :modules_array, :positions_array, social_media_modules_attributes: [:id, :social_media_type, :social_media_value]))
         redirect_to @vacancy
      else
         render 'edit'
      end
   end

   def destroy
      @vacancy = Vacancy.find(params[:id])
      @vacancy.destroy

      redirect_to root_path
   end

   def update_with_modules
      @vacancy = Vacancy.find(params[:vacancy_id])
      modules_array = {}

      recived_modules = params[:addedModules]

      recived_modules.each do |i|

         module_hash = {}

         module_hash["name"] = params[:addedModules][i][:name]
         module_hash["horizontal_position"] = "Horizontal Position here"
         module_hash["vertical_position"] = "Vertical Postition here"
         module_hash["width"] = params[:addedModules][i][:width]
         module_hash["height"] = "Height here"

         modules_array[i] = module_hash

      end

      @vacancy.update_attributes(modules_array: modules_array)

      respond_to do |format|
        format.html
        format.js
      end
   end

   def get_modules
      @vacancy = Vacancy.find(params[:vacancy_id])
      render :json => @vacancy.modules_array
   end

   def wallet

   end

   private
      def vacancy_params
         params.require(:vacancy).permit(:title, :description, :demands, :branche, :education_level, :experience, :location_id, :modules_array, :positions_array, social_media_modules_attributes: [:id, :social_media_type, :social_media_value])
      end

end

app/helpers/vacancies_helper.rb
module VacanciesHelper
   def calculateDistance(reaction, locationId)
      return (reaction.distance_to(Location.find(locationId)) * 1.6).round(2)
   end
end

app/views/vacancies/_form.html.erb
<%= form_for @vacancy do |f| %>
<% if @vacancy.errors.any? %>
  <div id="errors">
     <h2><%= pluralize(@vacancy.errors.count, "error") %> prevented this vacancy from saving.</h2>
     <ul>
        <% @vacancy.errors.full_messages.each do |msg| %>
           <li><%= msg %></li>
        <% end %>
     </ul>
  </div>
<% end %>

<div class="form new-vac-form">

  <%= f.text_field :title, class: '', placeholder: 'Naam vacature' %>

  <%= f.text_area :description, class: '', placeholder: 'Bescrijving vacature' %>

  <div class="field">
     <%= f.label :location_id, "Locatie" %>
     <%= f.collection_select :location_id, Location.all, :id, :name, class: "styled-select select-location" %>
  </div>

  <%= f.text_area :demands, class: '', placeholder: 'Eisen' %>

  <%= f.text_field :branche, class: '', placeholder: 'Branche' %>

  <%= f.text_field :education_level, class: '', placeholder: 'Educatie Niveau' %>

   <!-- <span class="input input--kaede">
      <%= f.text_field :location, class: 'input__field input__field--kaede' %>
      <label class="input__label input__label--kaede" for="vacancy_location">
         <span class="input__label-content input__label-content--kaede"> Locatie </span>
      </label>
   </span> -->

  <%= f.text_area :experience, class: '', placeholder: 'Ervaring' %>

  <label for="">Mail voor sollicitanten die worden uitgenodigd voor een gesprek.</label>
  <textarea name="" id="bottom-border-radius" cols="30" rows="10" placeholder="Tekst"> </textarea>

  <label for="">Mail voor sollicitanten die een twijfelgeval zijn.</label>
  <textarea name="" id="bottom-border-radius" cols="30" rows="10" placeholder="Tekst"> </textarea>

  <label for="">Mail voor sollicitanten die worden afgewezen.</label>
  <textarea name="" id="bottom-border-radius" cols="30" rows="10" placeholder="Tekst"> </textarea>

   <%= f.submit "Volgende stap", class: 'xpressy-button red-button' %>
</div>

<% end %>

app/views/vacancies/edit.html.erb
<h1>Vacature bewerken</h1>

<%= render 'form' %>

app/views/vacancies/index.html.erb
<div class="row options-bar">
  <div class="container">
  <div class="col-sm-4 col-md-4 col-lg-3">

    <%= form_tag vacancies_path, method: 'get' do %>
    <div class="input-group">
         <%= text_field_tag :search, params[:search], class: 'form-control', placeholder: 'Zoeken'%>
      <span class="input-group-btn">
        <%= button_tag(type: "submit", class: "btn btn-secondary") do %>
            <i class="fa fa-search"></i>
        <% end %>
      </span>
    </div>
    <% end %>
  </div>

  <div class="col-sm-4 col-md-4 col-lg-3">
    <div class="btn-group">
      <button type="button" class="btn btn-primary" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" id="btn-text">Filters</button>
      <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" id="btn-arrow">
        <span class="caret"></span>
        <span class="sr-only">Toggle Dropdown</span>
      </button>
      <ul class="dropdown-menu">
        <li><a href="#">Optie1</a></li>
      </ul>
    </div>
  </div>

  <div class="col-sm-4 col-md-4 col-lg-3 pull-right">
    <a href="vacancies/new">
      <div class="new-vac">
        Vacature Aanmaken <i class="fa fa-plus-circle fa-1x pull-right" aria-hidden="true"></i>
      </div>
    </a>
  </div>
</div>
</div>

<div class="flash-notice-space">
   <% flash.each do |key, value| %>
      <div class="alert alert-success">
         <a href="#" data-dismiss="alert" class="close-success">x</a>
         <ul>
            <li><%= value %></li>
         </ul>
      </div>
      <!-- <%= content_tag :div, value, :class => "flash #{key}" unless value.blank? %> -->
    <% end %>
</div>

<div class="container">

<div class="row">
<% @vacancies.each do |vacancy| %>

  <div class="col-sm-6 col-md-4 col-lg-3">

    <div class="vacancy-box">

      <div class="vacancy-wrapper">
          <i class="fa fa-code fa-5x" aria-hidden="true"></i>
         <h2 class="title"><%= link_to vacancy.title, vacancy %></h2>


        <div class="vacancy-overlay">
<!--           <% if vacancy.online %>
             <input type="radio" name="on_off_<%= vacancy.id %>" value="on" checked="checked"> On
             <input type="radio" name="on_off_<%= vacancy.id %>" value="off"> Off
          <% else %>
            <input type="radio" name="on_off_<%= vacancy.id %>" value="on"> On
            <input type="radio" name="on_off_<%= vacancy.id %>" value="off" checked="checked"> Off
          <% end %> -->

          <span class="vacancy-option">
            <i class="fa fa-power-off" aria-hidden="true"></i>
            <div class="onoffswitch">
                <input type="checkbox" name="onoffswitch" class="onoffswitch-checkbox" id="myonoffswitch" checked>
                <label class="onoffswitch-label" for="myonoffswitch">
                    <span class="onoffswitch-inner"></span>
                    <span class="onoffswitch-switch"></span>
                </label>
            </div>
            </span> <br>

          <span class="vacancy-option"> <i class="fa fa-eye" aria-hidden="true"></i> <%= link_to "Reacties Inzien", vacancy %> </span> <br>
          <span class="vacancy-option"> <i class="fa fa-pencil" aria-hidden="true"></i> <%= link_to "Vacature Bewerken", edit_vacancy_path(vacancy) %> </span>
        </div>

    </div>
</div>
<!--     <div class="vacancy-options">
      <%= link_to "Bewerken", edit_vacancy_path(vacancy) %>
-->


  </div>
<% end %>
</div>

</div>

app/views/vacancies/new.html.erb
<!-- Deel 1: Basisgegevens -->
<header class="sub-header form-title">
  <center> <h3>Vacature aanmaken - Basisgegeven invullen</h3></center>
</header>

<div class="content-wrap">
  <%= render 'form' %>
</div><!-- /content -->

<div class="progress-bar">
   <div class="progress-bar-content">
     <!-- <a href="#" class="pull-left"> <i class="fa fa-arrow-left" aria-hidden="true"></i></a> -->
     <span class="progress-bar-item active"><span class="progress-bar-number">1</span>Basis Gegevens</span>
     <span class="progress-bar-item"><span class="progress-bar-number">2</span>Modules toevoegen</span>
     <span class="progress-bar-item"><span class="progress-bar-number">3</span>Opslaan</span>
     <!-- <a href="#" class="pull-right" style="margin-right: 0;"> <i class="fa fa-arrow-right" aria-hidden="true"></i></a> -->
   </div>
</div>

app/views/vacancies/show.html.erb
<div class="container">
<div class="row">
  <div class="col-sm-3 vacancy-candidates">

   <% if user_signed_in? %>
    <div class="buttons">
      <%= link_to (raw('Vacature Verwijderen <i class="fa fa-times" aria-hidden="true"></i>')), vacancy_path(@vacancy), method: :delete, data: { confirm: 'Weet u het zeker dat u deze vacature wilt verwijderen?' }, class:"button-red" %><br /><br />

      <%= link_to (raw('Vacature Bewerken <i class="fa fa-pencil" aria-hidden="true"></i>')), edit_vacancy_path(@vacancy), class:"button-red" %>
      <br /><br />

      <a href="#" class="button-red">Plaats in portefeuille <i class="fa fa-star" aria-hidden="true"></i></a>
    </div>
   <% end %>

    <div class="filters">
      <a href="#" class="on">MBO4 X</a> |
      <a href="#" class="off">HBO -</a> |
      <a href="#" class="off">HTML -</a> |
      <a href="#" class="on">CSS X</a>|
      <a href="#" class="on">PHP X</a> <br>
    </div>

    <div class="reactions">
    <% @vacancy.reactions.each_with_index do |reaction, index| %>
      <div class='reaction <% if index == 0 %> active <% end %>'>
        <%= link_to reaction.first_name + ' ' + reaction.last_name, vacancy_reaction_path(@vacancy, reaction) %>

         <%= calculateDistance(reaction, @vacancy.location_id) %> km

        <div class="pull-right reaction-icons">
          <%= link_to (raw('<i class="fa fa-times fa-fw cross" aria-hidden="true"></i>')), vacancy_reaction_path(@vacancy, reaction), method: :delete, data: { confirm: 'Weet u zeker dat u deze reactie wilt verwijderen?' }, class:"" %>
          <%= link_to (raw('<i class="fa fa-question fa-fw question" aria-hidden="true"></i>')), edit_vacancy_path(@vacancy), class:"" %>
          <%= link_to (raw('<i class="fa fa-check fa-fw check" aria-hidden="true"></i>')), edit_vacancy_path(@vacancy), class:"" %>
        </div>
      </div>
    <% end %>

      <div class="reaction-form">
         <%= render 'reactions/form' %>
      </div>
    </div>
  </div>

  <div class="col-sm-9 xpressheet">
     <script>

       $.ajax({
          type: "POST",
          url: "../../../vacancies/" + <%= params[:id] %> + "/get_modules"
       }).done(function (response) {
          console.log(response);
          buildVacancy(response);
       });

       function buildVacancy(modules_from_db) {
          $.each(modules_from_db, function(index) {
              $("#modules-from-db").append("<div class='selected-module' data-width='" + modules_from_db[index]["width"] + "'><span class='module-text'>" + modules_from_db[index]["name"] + "</span></div>");
          });

          $(".selected-module").css('width', function() {
              return (($(this).data("width") * 23) + "%" );
          });
       }
     </script>

     <div id="modules-from-db" class="modules-container">

     </div>

    <!-- <img src="http://placehold.it/1000x1000" class="img-responsive"> -->
  </div>
</div>
<!-- <div class="col-md-4">
   <div id="reaction">
      <h2><%= @vacancy.reactions.count %> Reactions</h2>
      <%= render @vacancy.reactions %>
   </div>
</div>

<div class="col-md-4">
   <h3>Add a reaction</h3>
   <%= render 'reactions/form' %>
</div> -->

app/views/vacancies/wallet.html.erb
<div class="container">
<div class="row">
  <div class="col-sm-3 sidenav">
    <div class="vacancy active">
      <p>Visual Design <i class="fa fa-arrow-right pull-right" aria-hidden="true"></i></p>
    </div>
    <div class="vacancy">
      <p>Front end dev <i class="fa fa-arrow-right pull-right" aria-hidden="true"></i></p>
    </div>
    <div class="vacancy">
      <p>Backend dev <i class="fa fa-arrow-right pull-right" aria-hidden="true"></i></p>
    </div>
    <div class="vacancy">
      <p>Online marketeer <i class="fa fa-arrow-right pull-right" aria-hidden="true"></i></p>
    </div>
  </div>

  <div class="col-sm-3 sidenav">
    <div class="candidate">
      <p>Karen Wiersma</p>
    </div>
    <div class="candidate">
      <p>Brum Honingh</p>
    </div>
    <div class="candidate">
      <p>Coen Slet</p>
    </div>
    <div class="candidate">
      <p>Kim Bilstra</p>
    </div>
    <div class="candidate active">
      <p>Niels Ettema</p>
    </div>
    <div class="candidate">
      <p>Koen van der Baan</p>
    </div>

  </div>

  <div class="col-sm-6">
    <img src="http://placehold.it/1000x1000" class="img-responsive">
  </div>
</div>
</div>