config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }
  resources :users, except: :create
  get 'create_user' => 'users#add_new_user', as: :new_user_by_admin
  post 'create_user' => 'users#create', as: :create_user
  get 'wallet' => 'vacancies#wallet'


  post 'vacancies/:vacancy_id/update_with_modules', to: 'vacancies#update_with_modules'
  post 'vacancies/:vacancy_id/get_modules', to: 'vacancies#get_modules'

  # devise_for :users, controllers: {
  #       sessions: 'users/sessions'
  #     }

  resources :vacancies do
     resources :reactions
     resources :vacancy_steps
     resources :vacancy_modules
  end

  # resources :vacancy_steps
  resources :companies do
     resources :locations
  end

  root "vacancies#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord
   has_many :locations, dependent: :destroy
   validates :name, presence: true, length: { minimum: 5 }
   validates :description, presence: true
   validates :address, presence: true
   validates :postal_code, presence: true
   validates :city, presence: true
end

app/models/location.rb
class Location < ApplicationRecord
   belongs_to :company

   geocoded_by :full_address
   after_validation :geocode, :if => :postal_code_changed?

   def full_address
      [postal_code, city].compact.join(', ')
   end
end

app/models/reaction.rb
class Reaction < ApplicationRecord
  belongs_to :vacancy

  geocoded_by :full_address
  after_validation :geocode, :if => :postal_code_changed?

  def full_address
     [postal_code, city].compact.join(', ')
  end
end

app/models/social_media_module.rb
class SocialMediaModule < ApplicationRecord
  belongs_to :vacancy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

   has_attached_file :avatar, styles: { medium: "300x300>", thumb: "50x50>" }, default_url: ":style/missing.png"
   validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
end

app/models/vacancy.rb
class Vacancy < ApplicationRecord
   has_many :reactions, dependent: :destroy
   has_many :social_media_modules, dependent: :destroy
   # has_many :location

   attr_accessor :name, :module_horizontal_position, :module_vertical_position, :module_width, :module_height

   #contact-gegevens-module
   attr_accessor :contact_fields_name, :contact_fields_horizontal_position, :contact_fields_vertical_position, :contact_fields_width, :contact_fields_height

   #social-media-module
   attr_accessor :social_media_name, :social_media_horizontal_position, :social_media_vertical_position, :social_media_width, :social_media_height

   accepts_nested_attributes_for :social_media_modules

   serialize :modules_array, Hash

   def self.search(search)
      where("title LIKE ?", "%#{search}%")
   end

end

app/models/vacancy_module.rb
class VacancyModule < ApplicationRecord
  belongs_to :vacancy
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController

   def index
      @companies = Company.all.includes(:locations)
   end

   def new
      if (Company.exists?)
         flash[:notice] = 'There is already a company defined, you can edit this company.'
         redirect_to companies_path
      else
         @company = Company.new
      end
   end

   def create
      @company = Company.new(company_params)

      if @company.save
         redirect_to @company
      else
         render 'new'
      end
   end

   def show
      @company = find_company
   end

   def edit
      @company = find_company
   end

   def update
      @company = find_company

      if @company.update(params[:company].permit(:name, :description, :address, :postal_code, :city))
         redirect_to @company
      else
         render 'edit'
      end
   end

   def destroy
      @company = find_company
      @company.destroy

      flash[:notice] = 'The company has succesfully been destoyed.'
      redirect_to root_path
   end

   private
      def company_params
         params.require(:company).permit(:name, :description, :address, :postal_code, :city)
      end

      def find_company
         Company.find(params[:id])
      end
end

app/controllers/reactions_controller.rb
class ReactionsController < ApplicationController

   def create
      @vacancy = Vacancy.find(params[:vacancy_id])
      @reaction = @vacancy.reactions.create(params[:reaction].permit(:first_name, :last_name, :email, :age, :education, :body, :address, :postal_code, :city, :country))

      redirect_to vacancy_path(@vacancy)
   end

   def destroy
      @vacancy = Vacancy.find(params[:vacancy_id])
      @reaction = @vacancy.reactions.find(params[:id])
      @reaction.destroy

      redirect_to vacancy_path(@vacancy)
   end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
   # before_filter :authorize_admin, only: :create
   before_action :authorize_admin
   before_action :get_companies

   def add_new_user
      render 'new'
   end

   def get_companies
      @companies = Company.all
   end

   def create
      @user = User.new(user_params)
      @user.save
      redirect_to root_path, alert: 'New user has been created.'
   end

   private
      def authorize_admin
         if(current_user)
            if (current_user.admin?)
               return
            else
               redirect_to root_path, alert: 'You do not have the rights to view this page.'
            end
         elsif (User.count == 0)
            return
         else
            redirect_to root_path, alert: 'You do not have the rights to view this page.'
         end
      end

      def user_params
         params.require(:user).permit(:email, :first_name, :last_name, :admin, :password, :password_confirmation)
      end
end

app/helpers/application_helper.rb
module ApplicationHelper
   def active_tab(link_path)
      current_page?(link_path) ? "tab-current" : ""
   end

   def controller?(*controller)
      controller.include?(params[:controller])
   end

   def action?(*action)
    action.include?(params[:action])
  end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/company_helper.rb
module CompanyHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/modules_helper.rb
module ModulesHelper
end

app/helpers/reaction_helper.rb
module ReactionHelper
end

app/helpers/reactions_helper.rb
module ReactionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/vacancies_helper.rb
module VacanciesHelper
   def calculateDistance(reaction, locationId)
      return (reaction.distance_to(Location.find(locationId)) * 1.6).round(2)
   end
end

app/helpers/vacancy_modules_helper.rb
module VacancyModulesHelper
end

app/helpers/vacancy_steps_helper.rb
module VacancyStepsHelper
end

app/views/reactions/_form.html.erb
<%= form_for([@vacancy, @vacancy.reactions.build]) do |f| %>

   <p>
      <%= f.label :first_name %><br />
      <%= f.text_field :first_name %>
   </p>

   <p>
      <%= f.label :last_name %><br />
      <%= f.text_field :last_name %>
   </p>

   <p>
      <%= f.label :address %><br />
      <%= f.text_field :address %>
   </p>

   <p>
      <%= f.label :postal_code %><br />
      <%= f.text_field :postal_code %>
   </p>

   <p>
      <%= f.label :city %><br />
      <%= f.text_field :city %>
   </p>

   <p>
      <%= f.label :country %><br />
      <%= f.text_field :country %>
   </p>

   <p>
      <%= f.label :age %><br />
      <%= f.number_field :age %>
   </p>

   <p>
      <%= f.label :email %><br />
      <%= f.text_field :email %>
   </p>

   <p>
      <%= f.label :education %><br />
      <%= f.text_field :education %>
   </p>

   <p>
      <%= f.label :body %><br />
      <%= f.text_area :body %>
   </p>

   <p>
      <%= f.submit %>
   </p>

<% end %>

app/views/reactions/_reaction.html.erb
<div class="col-md-6 reaction-wrapper">
   <p>
      <b>First Name: </b><br />
      <%= reaction.first_name %>
   </p>
   <p>
      <b>Last Name: </b><br />
      <%= reaction.last_name %>
   </p>
   <p>
      <b>Address: </b><br />
      <%= reaction.address %>
   </p>
   <p>
      <b>Postal Code: </b><br />
      <%= reaction.postal_code %>
   </p>
   <p>
      <b>City: </b><br />
      <%= reaction.city %>
   </p>
   <p>
      <b>Country: </b><br />
      <%= reaction.country %>
   </p>
   <p>
      <b>Email: </b><br />
      <%= reaction.email %>
   </p>
   <p>
      <b>Age: </b><br />
      <%= reaction.age %>
   </p>
   <p>
      <b>Education: </b><br />
      <%= reaction.education %>
   </p>
   <p>
      <b>Reaction: </b><br />
      <%= reaction.body %>
   </p>

   <% if user_signed_in? %>
      <p><%= link_to "Delete", [reaction.vacancy, reaction], method: :delete, data: { confirm: "Are you sure?" } %></p>
   <% end %>

   <br />
</div>

app/views/reactions/show.html.erb
<header class="sub-header">
   <ul>
      <li><%= link_to "Back", vacancies_path(:vacancy_id) %></li>

      <% if user_signed_in? %>
         |
         <li><%= link_to "Edit", edit_vacancy_reaction_path(params[:vacancy_id], params[:id]) %></li>
         |
         <li><%= link_to "Delete", vacancy_reaction_path(params[:vacancy_id], params[:id]), method: :delete, data: { confirm: 'Are you sure?' } %></li>
      <% end %>
   </ul>
</header>

<div class="location-info">
   <h1 class="name">
      <%= @reaction.name %>
   </h1>

   <p class="address">
      <b>Address:</b><br />
      <%= @reaction.address %>
   </p>

   <p class="postal_code">
      <b>Postal Code:</b><br />
      <%= @reaction.postal_code %>
   </p>

   <p class="city">
      <b>City:</b><br />
      <%= @reaction.city %>
   </p>

   <p class="country">
      <b>County:</b><br />
      <%= @reaction.country %>
   </p>

   <p class="longitude">
      <b>Longitude:</b><br />
      <%= @reaction.longitude %>
   </p>

   <p class="latitude">
      <b>Latitude:</b><br />
      <%= @reaction.latitude %>
   </p>
</div>