config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }
  resources :users, except: :create
  get 'create_user' => 'users#add_new_user', as: :new_user_by_admin
  post 'create_user' => 'users#create', as: :create_user
  get 'wallet' => 'vacancies#wallet'


  post 'vacancies/:vacancy_id/update_with_modules', to: 'vacancies#update_with_modules'
  post 'vacancies/:vacancy_id/get_modules', to: 'vacancies#get_modules'

  # devise_for :users, controllers: {
  #       sessions: 'users/sessions'
  #     }

  resources :vacancies do
     resources :reactions
     resources :vacancy_steps
     resources :vacancy_modules
  end

  # resources :vacancy_steps
  resources :companies do
     resources :locations
  end

  root "vacancies#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord
   has_many :locations, dependent: :destroy
   validates :name, presence: true, length: { minimum: 5 }
   validates :description, presence: true
   validates :address, presence: true
   validates :postal_code, presence: true
   validates :city, presence: true
end

app/models/location.rb
class Location < ApplicationRecord
   belongs_to :company

   geocoded_by :full_address
   after_validation :geocode, :if => :postal_code_changed?

   def full_address
      [postal_code, city].compact.join(', ')
   end
end

app/models/reaction.rb
class Reaction < ApplicationRecord
  belongs_to :vacancy

  geocoded_by :full_address
  after_validation :geocode, :if => :postal_code_changed?

  def full_address
     [postal_code, city].compact.join(', ')
  end
end

app/models/social_media_module.rb
class SocialMediaModule < ApplicationRecord
  belongs_to :vacancy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

   has_attached_file :avatar, styles: { medium: "300x300>", thumb: "50x50>" }, default_url: ":style/missing.png"
   validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
end

app/models/vacancy.rb
class Vacancy < ApplicationRecord
   has_many :reactions, dependent: :destroy
   has_many :social_media_modules, dependent: :destroy
   # has_many :location

   attr_accessor :name, :module_horizontal_position, :module_vertical_position, :module_width, :module_height

   #contact-gegevens-module
   attr_accessor :contact_fields_name, :contact_fields_horizontal_position, :contact_fields_vertical_position, :contact_fields_width, :contact_fields_height

   #social-media-module
   attr_accessor :social_media_name, :social_media_horizontal_position, :social_media_vertical_position, :social_media_width, :social_media_height

   accepts_nested_attributes_for :social_media_modules

   serialize :modules_array, Hash

   def self.search(search)
      where("title LIKE ?", "%#{search}%")
   end

end

app/models/vacancy_module.rb
class VacancyModule < ApplicationRecord
  belongs_to :vacancy
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController

   def index
      @companies = Company.all.includes(:locations)
   end

   def new
      if (Company.exists?)
         flash[:notice] = 'There is already a company defined, you can edit this company.'
         redirect_to companies_path
      else
         @company = Company.new
      end
   end

   def create
      @company = Company.new(company_params)

      if @company.save
         redirect_to @company
      else
         render 'new'
      end
   end

   def show
      @company = find_company
   end

   def edit
      @company = find_company
   end

   def update
      @company = find_company

      if @company.update(params[:company].permit(:name, :description, :address, :postal_code, :city))
         redirect_to @company
      else
         render 'edit'
      end
   end

   def destroy
      @company = find_company
      @company.destroy

      flash[:notice] = 'The company has succesfully been destoyed.'
      redirect_to root_path
   end

   private
      def company_params
         params.require(:company).permit(:name, :description, :address, :postal_code, :city)
      end

      def find_company
         Company.find(params[:id])
      end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
   before_action :find_company, only: [:new, :create, :edit, :update]

   def index
      @locations = Location.all
   end

   def new
      @company= Company.find(params[:company_id])
      @location = Location.new
   end

   def create
      # @location = Location.new(location_params)
      @location = @company.locations.create(location_params)

      if @location.save
         redirect_to @company
      else
         render 'new'
      end
   end

   def show
      @location = Location.find(params[:id])
   end

   def edit
      @location = Location.find(params[:id])
   end

   def update
      @location = Location.find(params[:id])

      if @location.update(params[:location].permit(:name, :address, :postal_code, :city, :country))
         redirect_to @company
      else
         render 'edit'
      end
   end

   def destroy
      @location = Location.find(params[:id])
      @location.destroy

      redirect_to root_path
   end

   private
      def location_params
         params.require(:location).permit(:name, :address, :postal_code, :city, :country, :company_id)
      end

      def find_company
         @company = Company.find(params[:company_id])
      end
end

app/controllers/reactions_controller.rb
class ReactionsController < ApplicationController

   def create
      @vacancy = Vacancy.find(params[:vacancy_id])
      @reaction = @vacancy.reactions.create(params[:reaction].permit(:first_name, :last_name, :email, :age, :education, :body, :address, :postal_code, :city, :country))

      redirect_to vacancy_path(@vacancy)
   end

   def destroy
      @vacancy = Vacancy.find(params[:vacancy_id])
      @reaction = @vacancy.reactions.find(params[:id])
      @reaction.destroy

      redirect_to vacancy_path(@vacancy)
   end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
   # before_filter :authorize_admin, only: :create
   before_action :authorize_admin
   before_action :get_companies

   def add_new_user
      render 'new'
   end

   def get_companies
      @companies = Company.all
   end

   def create
      @user = User.new(user_params)
      @user.save
      redirect_to root_path, alert: 'New user has been created.'
   end

   private
      def authorize_admin
         if(current_user)
            if (current_user.admin?)
               return
            else
               redirect_to root_path, alert: 'You do not have the rights to view this page.'
            end
         elsif (User.count == 0)
            return
         else
            redirect_to root_path, alert: 'You do not have the rights to view this page.'
         end
      end

      def user_params
         params.require(:user).permit(:email, :first_name, :last_name, :admin, :password, :password_confirmation)
      end
end

app/helpers/application_helper.rb
module ApplicationHelper
   def active_tab(link_path)
      current_page?(link_path) ? "tab-current" : ""
   end

   def controller?(*controller)
      controller.include?(params[:controller])
   end

   def action?(*action)
    action.include?(params[:action])
  end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/company_helper.rb
module CompanyHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/modules_helper.rb
module ModulesHelper
end

app/helpers/reaction_helper.rb
module ReactionHelper
end

app/helpers/reactions_helper.rb
module ReactionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/vacancies_helper.rb
module VacanciesHelper
   def calculateDistance(reaction, locationId)
      return (reaction.distance_to(Location.find(locationId)) * 1.6).round(2)
   end
end

app/helpers/vacancy_modules_helper.rb
module VacancyModulesHelper
end

app/helpers/vacancy_steps_helper.rb
module VacancyStepsHelper
end

app/views/companies/_form.html.erb
<%= form_for @company do |f| %>
   <% if @company.errors.any? %>
      <div id="errors">
         <h2><%= pluralize(@company.errors.count, "error") %> prevented this vacancy from saving.</h2>
         <ul>
            <% @company.errors.full_messages.each do |msg| %>
               <li><%= msg %></li>
            <% end %>
         </ul>
      </div>
   <% end %>
   <div class="form">
      <h1>Bedrijfsgegevens bewerken</h1>

         <%= f.text_field :name, placeholder: "Naam" %>

         <%= f.text_area :description, placeholder: "Beschrijving" %>

         <%= f.text_field :address, placeholder: "Adres" %>

         <%= f.text_area :postal_code, placeholder: "Postcode" %>

         <%= f.text_field :city, placeholder: "Stad" %>

         <%= f.submit "Opslaan", class: "xpressy-button green-button" %>
      </p>
   </div>

<% end %>

app/views/companies/edit.html.erb
<div class="user-wrapper">

	<header class="sub-header">
	   <ul>
	      <li><%= link_to "Back", companies_path %></li>

	      <% if user_signed_in? %>
	         |
	         <li><%= link_to "Delete", company_path(@company), method: :delete, data: { confirm: 'Are you sure?' } %></li>
	      <% end %>
	   </ul>
	</header>

	<h1>Bedrijfsgegevens aanpassen</h1>

	<%= render 'form' %>
</div>

app/views/companies/index.html.erb
<% if Company.exists? %>
   <!-- <% @companies.each do |company| %>
      <h3><%= link_to 'View locations', company_locations_path(company) %></h3>
   <% end %> -->
<% end %>

<div class="container">
<div class="row">
   <% @companies.each do |company| %>
  <div class="col-sm-3 sidenav">
    <%= link_to (raw('<p class="active">Bedrijfsgegevens<i class="fa fa-arrow-right pull-right" aria-hidden="true"></i></p>')), companies_path, class:"" %>
    <%= link_to (raw('<p>Bedrijfslocatie toevoegen<i class="fa fa-arrow-right pull-right" aria-hidden="true"></i></p>')), new_company_location_path(company), class:"" %>
    <%= link_to (raw('<p>Gebruiker toevoegen<i class="fa fa-arrow-right pull-right" aria-hidden="true"></i></p>')), new_user_path, class:"" %>
  </div>

   <div class="col-sm-9 company-container">

      <div class="company">
         <h1>Bedrijfsgegevens</h1>
         <ul>
            <li><h2><span class="list-title">Naam:</span> <%= company.name %></h2></li>
            <li><span class="list-title">Beschrijving: </span><%= company.description %></li>
            <li><span class="list-title">Adres: </span><%= company.address %></li>
            <li><span class="list-title">Postcode: </span><%= company.postal_code %></li>
            <li><span class="list-title">Stad: </span><%= company.city %></li>
         </ul>
         <%= link_to 'Bewerken', edit_company_path(company), class: "xpressy-button orange-button pull-right" %>
      </div>

      <div class="locations">
         <h1>Locaties</h1>
      <% company.locations.each do |location| %>
         <div class="location">
            <ul>
               <li><h2><span class="list-title">Naam: </span><%= location.name %></h2></li>
               <li><span class="list-title">Adres: </span><%= location.address %></li>
               <li><span class="list-title">Postcode: </span><%= location.postal_code %></li>
               <li><span class="list-title">Stad: </span><%= location.city %></li>
            </ul>
            <%= link_to 'Locatie Verwijderen', company_location_path(company, location), method: :delete, data: { confirm: "Are you sure?" }, class: "xpressy-button red-button pull-right" %>
            <%= link_to 'Locatie Bewerken', edit_company_location_path(company, location), class: "xpressy-button orange-button pull-right" %>
         </div>
      <% end %>
      </div>
   </div>

  <% end %>
</div>
</div>

   <!-- <h1 style="text-align:center;"><%= link_to "Voeg een nieuwe locatie toe", new_company_location_path(@companies.ids) %></h1>
   <% @companies.each do |company| %>
      <div class="col-md-3">
         <% company.locations.each do |location| %>
            <h1 style="text-align:center;"><%= location.name %></h1>
            <p>
               <b>Address</b><br />
               <%= location.address %>
            </p>
            <p>
               <b>Postal Code</b><br />
               <%= location.postal_code %>
            </p>
            <p>
               <b>City</b><br />
               <%= location.city %>
            </p>
            <p>
               <b>Country</b><br />
               <%= location.country %>
            </p>
            <p>
               <b><%= link_to 'Edit', edit_company_location_path(company, location) %></b><br />

               <b><%= link_to 'Delete', company_location_path(company, location), method: :delete, data: { confirm: "Are you sure?" } %></b>
            </p>
         <% end %>
      </div>
   <% end %>

   <div class="company-wrapper">
      <% if Company.exists? %>
         <% @companies.each do |company| %>
            <h2 class="title" style="text-align: center"><%= company.name %></h2>
            <div class="container">
               <p class="description">
                  <b>Description: </b><br />
                  <%= company.description %>
               </p>

               <p class="address">
                  <b>Address: </b><br />
                  <%= company.address %>
               </p>

               <p class="postal_code">
                  <b>Postal Code: </b><br />
                  <%= company.postal_code %>
               </p>

               <p class="city">
                  <b>City: </b><br />
                  <%= company.city %>
               </p>

               <p class="edit-company">
                  <%= link_to 'Edit Company', edit_company_path(company) %>
               </p>
            </div>
         <% end %>

         <% if user_signed_in? %>
          <% if current_user.admin? %>
            <li class="<%= active_tab(new_user_by_admin_path) %>"><%= link_to (raw('<span>Sign Up New User</span>')), new_user_by_admin_path, class:"" %></a></li>
          <% end %>
         <% end %>

      <% else %>
         <h2 class="title"><%= link_to 'Create company', new_company_path %></h2>

      <% end %>
  </div>
</div>

<div class="col-md-9">
   <h1 style="text-align:center;"><%= link_to "Voeg een nieuwe locatie toe", new_company_location_path(@companies.ids) %></h1>
   <% @companies.each do |company| %>
      <div class="col-md-3">
         <% company.locations.each do |location| %>
            <h1 style="text-align:center;"><%= location.name %></h1>
            <p>
               <b>Address</b><br />
               <%= location.address %>
            </p>
            <p>
               <b>Postal Code</b><br />
               <%= location.postal_code %>
            </p>
            <p>
               <b>City</b><br />
               <%= location.city %>
            </p>
            <p>
               <b>Country</b><br />
               <%= location.country %>
            </p>
            <p>
               <b>Longitude</b><br />
               <%= location.longitude %>
            </p>
            <p>
               <b>Latitude</b><br />
               <%= location.latitude %>
            </p>
            <p>
               <b><%= link_to 'Edit', edit_company_location_path(company, location) %></b><br />

               <b><%= link_to 'Delete', company_location_path(company, location), method: :delete, data: { confirm: "Are you sure?" } %></b>
            </p>
         <% end %>
      </div>
   <% end %>
 -->

app/views/companies/new.html.erb
<div class="user-wrapper">

	<h1>Nieuw bedrijf toevoegen</h1>

	<%= render 'form' %>
</div>

app/views/companies/show.html.erb
<div class="user-wrapper">

   <header class="sub-header">
      <ul>
         <li><%= link_to "Back", companies_path %></li>

         <% if user_signed_in? %>
            |
            <li><%= link_to "Edit", edit_company_path(@company) %></li>
            |
            <li><%= link_to "Delete", company_path(@company), method: :delete, data: { confirm: 'Are you sure?' } %></li>
         <% end %>
      </ul>
   </header>

   <div class="col-md-4 company-info">
      <h1 class="title">
         <%= @company.name %>
      </h1>

      <p class="description">
         <b>Description:</b><br />
         <%= @company.description %>
      </p>

      <p class="address">
         <b>Address:</b><br />
         <%= @company.address %>
      </p>

      <p class="postal_code">
         <b>Postal Code:</b><br />
         <%= @company.postal_code %>
      </p>

      <p class="city">
         <b>City:</b><br />
         <%= @company.city %>
      </p>
   </div>
</div>